import type { ZivanComment, ZivanCommunity, ZivanNotification, ZivanPost, ZivanState, ZivanUser } from "./zivan-types";

export const ZIVAN_STORAGE_KEY = "zivan_state_v2";

export const ZIVAN_TOPICS = [
  "Anime & Cosplay",
  "Art",
  "Business & Finance",
  "Education & Career",
  "Fashion & Beauty",
  "Food & Drinks",
  "Games",
  "Health",
  "Home & Garden",
  "Internet Culture",
  "Movies & TV",
  "Music",
  "News & Politics",
  "Places & Travel",
  "Pop Culture",
  "Q&As & Stories",
  "Reading & Writing",
  "Sciences",
  "Sports",
  "Technology",
  "Vehicles",
  "Wellness",
];

const avatarGradients = [
  "linear-gradient(135deg, #8b5cf6, #312e81)",
  "linear-gradient(135deg, #c084fc, #4c1d95)",
  "linear-gradient(135deg, #a78bfa, #0f172a)",
  "linear-gradient(135deg, #7c3aed, #18181b)",
  "linear-gradient(135deg, #ddd6fe, #6d28d9)",
  "linear-gradient(135deg, #6d28d9, #020617)",
];

export const seedUsers: ZivanUser[] = [
  {
    id: "u_zivan_admin",
    username: "zivan_admin",
    email: "admin@zivan.test",
    password: "zivan123",
    avatar: avatarGradients[0],
    reputation: 18420,
    joinedAt: "2025-01-04T09:00:00.000Z",
    bio: "Building Zivan in public and collecting sharp community feedback.",
  },
  {
    id: "u_nova_builder",
    username: "nova_builder",
    email: "nova@zivan.test",
    password: "zivan123",
    avatar: avatarGradients[1],
    reputation: 4820,
    joinedAt: "2025-03-12T18:20:00.000Z",
    bio: "Product tinkerer, workflow nerd, and careful launcher.",
  },
  {
    id: "u_codecaster",
    username: "codecaster",
    email: "codecaster@zivan.test",
    password: "zivan123",
    avatar: avatarGradients[2],
    reputation: 6310,
    joinedAt: "2025-02-21T14:12:00.000Z",
    bio: "Writes about developer tools, browsers, and durable systems.",
  },
  {
    id: "u_nightowl",
    username: "nightowl",
    email: "nightowl@zivan.test",
    password: "zivan123",
    avatar: avatarGradients[3],
    reputation: 2105,
    joinedAt: "2025-08-02T02:45:00.000Z",
    bio: "Late-night reader. I save the best threads for morning.",
  },
  {
    id: "u_pixelmage",
    username: "pixelmage",
    email: "pixelmage@zivan.test",
    password: "zivan123",
    avatar: avatarGradients[4],
    reputation: 7988,
    joinedAt: "2025-04-17T11:10:00.000Z",
    bio: "Interface designer, poster collector, and tiny-detail advocate.",
  },
  {
    id: "u_orbit_reader",
    username: "orbit_reader",
    email: "orbit@zivan.test",
    password: "zivan123",
    avatar: avatarGradients[5],
    reputation: 3590,
    joinedAt: "2025-06-30T20:05:00.000Z",
    bio: "Science, cinema, and thoughtful questions.",
  },
];

export const seedCommunities: ZivanCommunity[] = [
  {
    id: "c_subzivan",
    name: "subzivan",
    topic: "Internet Culture",
    description: "The official community for Zivan updates, feedback, questions, and platform discussion.",
    privacy: "Public",
    mature: false,
    avatar: "linear-gradient(135deg, #c4b5fd, #6d28d9 55%, #0f0b1d)",
    banner: "linear-gradient(135deg, #120b24 0%, #4c1d95 48%, #111827 100%)",
    creatorId: "u_zivan_admin",
    createdAt: "2025-01-04T09:00:00.000Z",
    rules: [
      "Be relevant to Zivan",
      "No low-effort spam",
      "Use the right flair",
      "Respect other members",
      "Check previous posts before posting",
    ],
    memberIds: ["u_zivan_admin", "u_nova_builder", "u_codecaster", "u_nightowl", "u_pixelmage", "u_orbit_reader"],
    highlights: ["Launch notes", "Feedback queue", "Weekly questions"],
  },
  {
    id: "c_technology",
    name: "technology",
    topic: "Technology",
    description: "Semiconductors, software, networks, hardware, and the strange future arriving early.",
    privacy: "Public",
    mature: false,
    avatar: "linear-gradient(135deg, #8b5cf6, #1e1b4b)",
    banner: "linear-gradient(135deg, #09090b, #312e81 44%, #18181b)",
    creatorId: "u_codecaster",
    createdAt: "2025-02-02T16:30:00.000Z",
    rules: ["Link to original sources", "Explain acronyms", "No vendor flamewars"],
    memberIds: ["u_zivan_admin", "u_nova_builder", "u_codecaster", "u_nightowl", "u_orbit_reader"],
    highlights: ["Tooling", "Hardware", "Standards"],
  },
  {
    id: "c_gaming",
    name: "gaming",
    topic: "Games",
    description: "Game design, patch notes, quiet indies, loud releases, and clips worth replaying.",
    privacy: "Public",
    mature: false,
    avatar: "linear-gradient(135deg, #7c3aed, #0f172a)",
    banner: "linear-gradient(135deg, #10091f, #5b21b6 52%, #09090b)",
    creatorId: "u_nightowl",
    createdAt: "2025-02-18T22:00:00.000Z",
    rules: ["Tag spoilers", "No platform bait", "Credit creators"],
    memberIds: ["u_nightowl", "u_pixelmage", "u_orbit_reader", "u_nova_builder"],
    highlights: ["Indies", "Strategy", "Speedruns"],
  },
  {
    id: "c_newsroom",
    name: "newsroom",
    topic: "News & Politics",
    description: "Context-first news discussion with source links and calmer headlines.",
    privacy: "Restricted",
    mature: false,
    avatar: "linear-gradient(135deg, #a78bfa, #312e81)",
    banner: "linear-gradient(135deg, #111827, #4c1d95 55%, #1f2937)",
    creatorId: "u_zivan_admin",
    createdAt: "2025-03-03T12:00:00.000Z",
    rules: ["Use primary reporting", "Add context", "No duplicate breaking posts"],
    memberIds: ["u_zivan_admin", "u_codecaster", "u_orbit_reader"],
    highlights: ["World", "Policy", "Media"],
  },
  {
    id: "c_design",
    name: "design",
    topic: "Design",
    description: "Critique, systems, typography, color, and the craft behind interfaces.",
    privacy: "Public",
    mature: false,
    avatar: "linear-gradient(135deg, #ddd6fe, #7c3aed)",
    banner: "linear-gradient(135deg, #18181b, #6d28d9 50%, #0f0b1d)",
    creatorId: "u_pixelmage",
    createdAt: "2025-04-20T10:00:00.000Z",
    rules: ["Critique the work", "Show context", "No drive-by redesigns"],
    memberIds: ["u_pixelmage", "u_nova_builder", "u_zivan_admin", "u_codecaster"],
    highlights: ["Critique", "Type", "Systems"],
  },
  {
    id: "c_questions",
    name: "questions",
    topic: "Q&As & Stories",
    description: "A thoughtful place for practical, curious, and occasionally odd questions.",
    privacy: "Public",
    mature: false,
    avatar: "linear-gradient(135deg, #c084fc, #1f2937)",
    banner: "linear-gradient(135deg, #09090b, #581c87 60%, #18181b)",
    creatorId: "u_orbit_reader",
    createdAt: "2025-05-15T09:45:00.000Z",
    rules: ["Ask clearly", "Share what you tried", "Mark solved answers"],
    memberIds: ["u_orbit_reader", "u_nightowl", "u_nova_builder", "u_zivan_admin"],
    highlights: ["Solved", "Advice", "Deep dives"],
  },
  {
    id: "c_movies",
    name: "movies",
    topic: "Movies & TV",
    description: "Films, directors, scenes, soundtracks, and spoiler-aware recommendations.",
    privacy: "Public",
    mature: false,
    avatar: "linear-gradient(135deg, #8b5cf6, #020617)",
    banner: "linear-gradient(135deg, #0f0b1d, #4338ca 45%, #020617)",
    creatorId: "u_orbit_reader",
    createdAt: "2025-07-08T19:30:00.000Z",
    rules: ["Use spoiler tags", "Name release year", "Explain recommendations"],
    memberIds: ["u_orbit_reader", "u_pixelmage", "u_nightowl"],
    highlights: ["Watchlists", "Reviews", "Soundtracks"],
  },
  {
    id: "c_builders",
    name: "builders",
    topic: "Design",
    description: "Shipping logs, launch notes, tiny wins, and useful scars from making things.",
    privacy: "Public",
    mature: false,
    avatar: "linear-gradient(135deg, #a78bfa, #4c1d95)",
    banner: "linear-gradient(135deg, #050510, #5b21b6 52%, #111827)",
    creatorId: "u_nova_builder",
    createdAt: "2025-08-12T15:20:00.000Z",
    rules: ["Share progress", "Be specific", "No launch spam"],
    memberIds: ["u_nova_builder", "u_codecaster", "u_pixelmage", "u_zivan_admin"],
    highlights: ["Build logs", "Launches", "Lessons"],
  },
];

export const seedPosts: ZivanPost[] = [
  {
    id: "p_welcome",
    communityName: "subzivan",
    authorId: "u_zivan_admin",
    type: "text",
    title: "Welcome to Zivan — read this before posting",
    body: "Start here for platform updates, feedback etiquette, and the basics of building healthy Zivan communities. Bring questions, specific ideas, and examples.",
    flair: "Official",
    mature: false,
    createdAt: "2026-05-21T12:30:00.000Z",
    baseScore: 412,
  },
  {
    id: "p_feature_request",
    communityName: "subzivan",
    authorId: "u_zivan_admin",
    type: "text",
    title: "Feature request thread: what should we build next?",
    body: "Current shortlist: saved drafts, compact density controls, profile pins, moderation queues, and a better notification digest. Tell us what would change your day-to-day use.",
    flair: "Feedback",
    mature: false,
    createdAt: "2026-05-21T10:00:00.000Z",
    baseScore: 244,
  },
  {
    id: "p_highlights",
    communityName: "subzivan",
    authorId: "u_nova_builder",
    type: "text",
    title: "How should community highlights work?",
    body: "Should highlights be moderator-curated, vote-powered, time-limited, or a mix? I like the idea of weekly cards that help newcomers understand the current conversation.",
    flair: "Discussion",
    mature: false,
    createdAt: "2026-05-20T19:20:00.000Z",
    baseScore: 156,
  },
  {
    id: "p_ai_workflows",
    communityName: "technology",
    authorId: "u_codecaster",
    type: "link",
    title: "AI tools are changing junior developer workflows",
    body: "The strongest teams seem to pair AI assistance with tighter review habits and smaller tickets. What practices are actually holding up?",
    url: "https://developer.mozilla.org/en-US/blog/",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=360&q=80",
    flair: "Analysis",
    mature: false,
    createdAt: "2026-05-20T18:42:00.000Z",
    baseScore: 267,
  },
  {
    id: "p_local_models",
    communityName: "technology",
    authorId: "u_nightowl",
    type: "image",
    title: "What laptop specs are enough for local models?",
    body: "Curious where the practical floor is for hobby experiments: RAM, VRAM, battery hit, and whether external GPUs are worth the desk mess.",
    imageUrl: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=360&q=80",
    flair: "Hardware",
    mature: false,
    createdAt: "2026-05-20T08:15:00.000Z",
    baseScore: 154,
  },
  {
    id: "p_best_game_community",
    communityName: "gaming",
    authorId: "u_nightowl",
    type: "image",
    title: "What game has the best community right now?",
    body: "I am less interested in hype and more interested in places where experienced players actually help new people stick around.",
    imageUrl: "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1551103782-8ab07afd45c1?auto=format&fit=crop&w=360&q=80",
    flair: "Discussion",
    mature: false,
    createdAt: "2026-05-19T23:17:00.000Z",
    baseScore: 229,
  },
  {
    id: "p_patch_notes",
    communityName: "gaming",
    authorId: "u_pixelmage",
    type: "text",
    title: "Patch notes discussion thread",
    body: "Drop balance changes, bug fixes, and quality-of-life notes here. Please tag spoilers and explain why a change matters for people who missed the update.",
    flair: "Patch Notes",
    mature: false,
    createdAt: "2026-05-19T18:30:00.000Z",
    baseScore: 178,
  },
  {
    id: "p_daily_headlines",
    communityName: "newsroom",
    authorId: "u_orbit_reader",
    type: "link",
    title: "Daily discussion: major headlines and context",
    body: "A calmer thread for the day’s big stories. Add primary links, local context, and corrections as stories develop.",
    url: "https://www.reuters.com/",
    thumbnail: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=360&q=80",
    flair: "Daily",
    mature: false,
    createdAt: "2026-05-19T14:23:00.000Z",
    baseScore: 98,
  },
  {
    id: "p_verify_news",
    communityName: "newsroom",
    authorId: "u_codecaster",
    type: "link",
    title: "How do you verify breaking news?",
    body: "What are your practical checks before sharing a fast-moving story? I usually look for original sourcing, timestamp drift, and local reporting.",
    url: "https://apnews.com/",
    thumbnail: "https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=360&q=80",
    flair: "Media Literacy",
    mature: false,
    createdAt: "2026-05-19T09:05:00.000Z",
    baseScore: 132,
  },
  {
    id: "p_dark_dashboards",
    communityName: "design",
    authorId: "u_pixelmage",
    type: "image",
    title: "Show your dark-mode dashboard designs",
    body: "Dense, useful, and readable beats dramatic every time. Share screenshots, token notes, and contrast lessons.",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=360&q=80",
    flair: "Showcase",
    mature: false,
    createdAt: "2026-05-18T22:40:00.000Z",
    baseScore: 211,
  },
  {
    id: "p_dense_feeds",
    communityName: "design",
    authorId: "u_nova_builder",
    type: "text",
    title: "Best practices for dense feed layouts",
    body: "I am collecting patterns for high-information feeds that still feel calm: line height, action grouping, avatars, preview length, and hover states.",
    flair: "Guide",
    mature: false,
    createdAt: "2026-05-18T16:05:00.000Z",
    baseScore: 144,
  },
  {
    id: "p_ask_zivan",
    communityName: "questions",
    authorId: "u_orbit_reader",
    type: "text",
    title: "Ask Zivan: beginner questions thread",
    body: "No question is too basic here. Ask about posting, joining communities, profile reputation, formatting, or how to find good discussions.",
    flair: "Question",
    mature: false,
    createdAt: "2026-05-18T20:10:00.000Z",
    baseScore: 173,
  },
  {
    id: "p_missing_community",
    communityName: "questions",
    authorId: "u_zivan_admin",
    type: "text",
    title: "What community should exist here that does not yet?",
    body: "Pitch a community you would actually help grow. Bonus points for a name, topic, first three rules, and a welcome post idea.",
    flair: "Ideas",
    mature: false,
    createdAt: "2026-05-18T13:10:00.000Z",
    baseScore: 118,
  },
  {
    id: "p_movies_sound",
    communityName: "movies",
    authorId: "u_pixelmage",
    type: "text",
    title: "Films where the sound design does more worldbuilding than the script",
    body: "Looking for scenes that communicate place, power, or dread mostly through sound.",
    flair: "Recommendations",
    mature: false,
    createdAt: "2026-05-17T11:40:00.000Z",
    baseScore: 121,
  },
  {
    id: "p_builder_ship",
    communityName: "builders",
    authorId: "u_nova_builder",
    type: "image",
    title: "My launch checklist wall finally stopped looking chaotic",
    body: "Moved from scattered notes to a three-lane system: validate, ship, learn. The biggest win was deleting half the nice-to-have tasks.",
    imageUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
    thumbnail: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=360&q=80",
    flair: "Build Log",
    mature: false,
    createdAt: "2026-05-17T09:10:00.000Z",
    baseScore: 186,
  },
];

export const seedComments: ZivanComment[] = [
  {
    id: "cm_launch_1",
    postId: "p_welcome",
    authorId: "u_nova_builder",
    body: "The community naming is already clear. z/subzivan feels like a home base instead of a brand tax.",
    createdAt: "2026-05-21T12:48:00.000Z",
    baseScore: 42,
  },
  {
    id: "cm_launch_1_reply",
    postId: "p_welcome",
    parentId: "cm_launch_1",
    authorId: "u_zivan_admin",
    body: "That was exactly the goal: familiar enough to move fast, different enough to feel like its own place.",
    createdAt: "2026-05-21T13:02:00.000Z",
    baseScore: 51,
  },
  {
    id: "cm_launch_2",
    postId: "p_welcome",
    authorId: "u_pixelmage",
    body: "Please keep compact rows as the default. Dense feeds are useful when the typography is this calm.",
    createdAt: "2026-05-21T13:20:00.000Z",
    baseScore: 35,
  },
  {
    id: "cm_feature_1",
    postId: "p_feature_request",
    authorId: "u_codecaster",
    body: "Drafts and notification filters would do the most work for me. The rest can wait until communities are busier.",
    createdAt: "2026-05-21T10:30:00.000Z",
    baseScore: 28,
  },
  {
    id: "cm_highlights_1",
    postId: "p_highlights",
    authorId: "u_orbit_reader",
    body: "A rotating weekly highlight gives newcomers a softer landing than an always-on leaderboard.",
    createdAt: "2026-05-20T19:55:00.000Z",
    baseScore: 24,
  },
  {
    id: "cm_tokens_1",
    postId: "p_dense_feeds",
    authorId: "u_codecaster",
    body: "Action clusters matter. If vote, comment, react, and share are visually equal, the row stays scan-friendly.",
    createdAt: "2026-05-20T16:22:00.000Z",
    baseScore: 27,
  },
  {
    id: "cm_tokens_reply",
    postId: "p_dense_feeds",
    parentId: "cm_tokens_1",
    authorId: "u_pixelmage",
    body: "Agreed. I also like letting the thumbnail own a fixed width so the title never gets shoved around.",
    createdAt: "2026-05-20T16:33:00.000Z",
    baseScore: 19,
  },
  {
    id: "cm_focus_1",
    postId: "p_ask_zivan",
    authorId: "u_orbit_reader",
    body: "For first posts, pick the most specific community you can. Broad questions get better answers when the context is clear.",
    createdAt: "2026-05-18T20:35:00.000Z",
    baseScore: 31,
  },
  {
    id: "cm_game_1",
    postId: "p_best_game_community",
    authorId: "u_pixelmage",
    body: "The best communities I have seen have simple onboarding rituals and patient veterans.",
    createdAt: "2026-05-20T00:04:00.000Z",
    baseScore: 23,
  },
  {
    id: "cm_news_1",
    postId: "p_verify_news",
    authorId: "u_zivan_admin",
    body: "Timestamp drift is underrated. A story can be true and still be stale by the time it hits a feed.",
    createdAt: "2026-05-19T09:40:00.000Z",
    baseScore: 18,
  },
  {
    id: "cm_dashboard_1",
    postId: "p_dark_dashboards",
    authorId: "u_nightowl",
    body: "The best examples keep empty states as carefully styled as the busy states.",
    createdAt: "2026-05-18T23:04:00.000Z",
    baseScore: 16,
  },
];

export const seedNotifications: ZivanNotification[] = [
  {
    id: "n_demo_digest",
    userId: "u_zivan_admin",
    type: "demo",
    title: "Weekly digest is ready",
    message: "z/subzivan gained 3 new feedback threads this week.",
    href: "/z/subzivan",
    createdAt: "2026-05-21T15:00:00.000Z",
    read: false,
  },
  {
    id: "n_demo_design",
    userId: "u_pixelmage",
    type: "demo",
    title: "Your design thread is trending",
    message: "Members are discussing dense feed layout patterns in z/design.",
    href: "/z/design/comments/p_dense_feeds",
    createdAt: "2026-05-20T17:00:00.000Z",
    read: false,
  },
  {
    id: "n_demo_builder",
    userId: "u_nova_builder",
    type: "demo",
    title: "New comment on your beginner question thread",
    message: "orbit_reader shared posting advice for new members.",
    href: "/z/questions/comments/p_ask_zivan",
    createdAt: "2026-05-18T21:00:00.000Z",
    read: false,
  },
];

export function createSeedState(): ZivanState {
  return {
    version: 2,
    users: seedUsers,
    communities: seedCommunities,
    posts: seedPosts,
    comments: seedComments,
    votes: [],
    reactions: [
      { userId: "u_nova_builder", postId: "p_welcome", emoji: "spark" },
      { userId: "u_pixelmage", postId: "p_welcome", emoji: "spark" },
      { userId: "u_codecaster", postId: "p_ai_workflows", emoji: "spark" },
    ],
    savedPostIds: {},
    hiddenPostIds: {},
    notifications: seedNotifications,
    sessionUserId: undefined,
  };
}
